modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="icon.jpg" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
    modId="the_vault"
    mandatory=true
    versionRange="[1.18.2-3.0.0.0,)"
    ordering="AFTER"
    side="BOTH"